const INCREMENT = 'INCREMENT';
const INCREMENT_SOME = 'INCREMENT_SOME';
const DECREMENT = 'DECREMENT';
const RESET = 'RESET';

const ADD_CUSTOMER = 'ADD_CUSTOMER';
const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';

export {
  INCREMENT, DECREMENT, RESET, INCREMENT_SOME, ADD_CUSTOMER, REMOVE_CUSTOMER,
};
