const ADD_TODO = 'ADD_TODO';
const REMOVE_TODO = 'REMOVE_TODO';
const COMPLETE_TODO = 'COMPLETE_TODO';
const FILTER_TODO = 'FILTER_TODO';

const SHOW_ALL = 'SHOW_ALL';
const SHOW_COMPLETED = 'SHOW_COMPLETED';
const SHOW_DOING = 'SHOW_DOING0';

export { ADD_TODO, REMOVE_TODO, COMPLETE_TODO, FILTER_TODO };
export { SHOW_ALL, SHOW_COMPLETED, SHOW_DOING };
